/* Native routine registration.
 *
 * Without this the package relied on dynamic symbol lookup, which is why two
 * defects went undetected by R CMD check: dann2() was exported and documented
 * while no dann2_ symbol existed anywhere in the shared object, and nndist2
 * called withmean2 with one argument fewer than withmean2 declared. Registering
 * the entry points makes a missing symbol a load-time failure and pins the
 * argument count of every routine R calls.
 *
 * The counts below were generated by
 *   tools::package_native_routine_registration_skeleton(".")
 * and each was checked against the corresponding subroutine declaration in
 * src/ and against every call site in R/.
 */

#include <R_ext/RS.h>
#include <stdlib.h>
#include <R_ext/Rdynload.h>

extern void F77_NAME(dann)(void *, void *, void *, void *, void *, void *,
                           void *, void *, void *, void *, void *, void *,
                           void *, void *, void *, void *, void *, void *,
                           void *, void *, void *, void *, void *, void *);
extern void F77_NAME(dannsub)(void *, void *, void *, void *, void *, void *,
                              void *, void *, void *, void *, void *, void *,
                              void *, void *, void *, void *, void *, void *,
                              void *);
extern void F77_NAME(knn)(void *, void *, void *, void *, void *, void *,
                          void *, void *, void *, void *);
extern void F77_NAME(knncv)(void *, void *, void *, void *, void *, void *,
                            void *, void *, void *);
extern void F77_NAME(nndist)(void *, void *, void *, void *, void *, void *,
                             void *, void *, void *, void *, void *, void *,
                             void *, void *, void *, void *, void *, void *,
                             void *, void *, void *, void *);
extern void F77_NAME(nndist2)(void *, void *, void *, void *, void *, void *,
                              void *, void *, void *, void *, void *, void *,
                              void *, void *, void *, void *, void *, void *,
                              void *, void *, void *, void *, void *);

static const R_FortranMethodDef FortranEntries[] = {
    {"dann",    (DL_FUNC) &F77_NAME(dann),    24},
    {"dannsub", (DL_FUNC) &F77_NAME(dannsub), 19},
    {"knn",     (DL_FUNC) &F77_NAME(knn),     10},
    {"knncv",   (DL_FUNC) &F77_NAME(knncv),    9},
    {"nndist",  (DL_FUNC) &F77_NAME(nndist),  22},
    {"nndist2", (DL_FUNC) &F77_NAME(nndist2), 23},
    {NULL, NULL, 0}
};

void R_init_dann(DllInfo *dll)
{
    R_registerRoutines(dll, NULL, NULL, FortranEntries, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
